CREATE OR REPLACE FUNCTION FNC_CONSULTA_SALARIO_EMPREGADO
  (PEMPLOYEE_ID   IN NUMBER)
   RETURN NUMBER
IS 
  VSALARY  EMPLOYEES.SALARY%TYPE;
BEGIN
  SELECT SALARY
  INTO   VSALARY
  FROM   EMPLOYEES
  WHERE EMPLOYEE_ID = PEMPLOYEE_ID;
  RETURN (VSALARY);
EXCEPTION
  WHEN NO_DATA_FOUND THEN 
    RAISE_APPLICATION_ERROR(-20001, 'Empregado inexistente');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20002, 'Error ' || SQLCODE || ' - ' || SQLERRM);
END;

--Execute

DECLARE
  VEMPLOYEE_ID  EMPLOYEES.EMPLOYEE_ID%TYPE := 101;
  VSALARY       EMPLOYEES.SALARY%TYPE;
BEGIN
  VSALARY := FNC_CONSULTA_SALARIO_EMPREGADO(VEMPLOYEE_ID);
  DBMS_OUTPUT.PUT_LINE('Salario: ' || VSALARY);
END;