CREATE OR REPLACE FUNCTION FNC_CONSULTA_TITULO_CARGO_EMPREGADO
  (PJOB_ID   IN JOBS.JOB_ID%TYPE)
   RETURN VARCHAR2
IS 
  VJOB_TITLE JOBS.JOB_TITLE%TYPE;
BEGIN
  SELECT JOB_TITLE
  INTO   VJOB_TITLE
  FROM   JOBS
  WHERE  JOB_ID = PJOB_ID;
  RETURN (VJOB_TITLE);
EXCEPTION
  WHEN NO_DATA_FOUND THEN 
    RAISE_APPLICATION_ERROR(-20001, 'Job inexistente');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20002, 'Error ' || SQLCODE || ' - ' || SQLERRM);
END;

--EXECUTE

SELECT FNC_CONSULTA_TITULO_CARGO_EMPREGADO('IT_PROG')
FROM   dual;