CREATE OR REPLACE TYPE BODY RECTANGLE AS 
   MEMBER PROCEDURE DISPLAY IS 
   BEGIN 
      DBMS_OUTPUT.PUT_LINE('LENGTH: '|| LENGTH); 
      DBMS_OUTPUT.PUT_LINE('WIDTH: '|| WIDTH); 
   END DISPLAY;  
   ORDER MEMBER FUNCTION MEASURE(R RECTANGLE) RETURN NUMBER IS 
   BEGIN 
      IF(SQRT(SELF.LENGTH*SELF.LENGTH + SELF.WIDTH*SELF.WIDTH)> 
         SQRT(R.LENGTH*R.LENGTH + R.WIDTH*R.WIDTH)) THEN 
         RETURN(1); 
      ELSE 
         RETURN(-1); 
      END IF; 
   END MEASURE; 
END; 
/ 