CREATE OR REPLACE TYPE BODY RECTANGLE AS 
   MEMBER FUNCTION ENLARGE(INC NUMBER) RETURN RECTANGLE IS 
   BEGIN 
      RETURN RECTANGLE(SELF.LENGTH + INC, SELF.WIDTH + INC); 
   END ENLARGE;  
   MEMBER PROCEDURE DISPLAY IS 
   BEGIN  
      DBMS_OUTPUT.PUT_LINE('LENGTH: '|| LENGTH); 
      DBMS_OUTPUT.PUT_LINE('WIDTH: '|| WIDTH); 
   END DISPLAY;  
   MAP MEMBER FUNCTION MEASURE RETURN NUMBER IS 
   BEGIN 
      RETURN (SQRT(LENGTH*LENGTH + WIDTH*WIDTH)); 
   END MEASURE; 
END; 
/ 