CREATE OR REPLACE TRIGGER B_D_EMPLOYEES_S_TRG
BEFORE DELETE
ON EMPLOYEES
BEGIN
  IF  (TO_CHAR(SYSDATE, 'DAY') IN ('SATURDAY', 'SUNDAY') OR
       TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) NOT BETWEEN 8 AND 18) 
  THEN
       RAISE_APPLICATION_ERROR( -20001,'Only can delete employee in work hour ');
  END IF;
END;