CREATE OR REPLACE TRIGGER A_D_EMPLOYESS_R_TRG
  AFTER DELETE
  ON EMPLOYEES
  FOR EACH ROW
DECLARE
	VEVENT       EMPLOYEES_LOG.EVENT%TYPE := 'D';
	VEMPLOYEE_ID  EMPLOYEES_LOG.EMPLOYEE_ID%TYPE := :OLD.EMPLOYEE_ID;
BEGIN
	INSERT INTO EMPLOYEES_LOG
		(EMPLOYEES_LOG_ID, 
         DT_LOG, 
         USERS, 
         EVENT, 
         EMPLOYEE_ID, 
         SALARY_OLD, 
         SALARY_NEW)
	VALUES
		(EMPLOYEES_LOG_SEQ.NEXTVAL,
		 SYSDATE,
		 USER,
		 VEVENT,
		 VEMPLOYEE_ID,
		 :OLD.SALARY,
		 :NEW.SALARY);
END A_D_EMPLOYESS_R_TRG;