CREATE OR REPLACE PROCEDURE PRC_CURSOR_EMPLOYEES
  (PEMPLOYEES_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN PEMPLOYEES_CURSOR 
  FOR
	SELECT FIRST_NAME, LAST_NAME 
	FROM EMPLOYEES;
	
END PRC_CURSOR_EMPLOYEES;

