CREATE OR REPLACE PROCEDURE PRC_INCREASES_EMPLOYEE_SALARY 
  (PEMPLOYEE_ID   IN NUMBER,
   PPERCENT    IN NUMBER)
IS
BEGIN
  UPDATE EMPLOYEES 
  SET SALARY = SALARY * (1 + PPERCENT / 100)
  WHERE EMPLOYEE_ID = PEMPLOYEE_ID;

EXCEPTION
  WHEN OTHERS 
  THEN
     RAISE_APPLICATION_ERROR(-20001, 'Error: ' || SQLCODE || ' - ' || SQLERRM);
END;

BEGIN
  PRC_INCREASES_EMPLOYEE_SALARY (109,10);
  COMMIT;
END;