CREATE OR REPLACE PROCEDURE PRC_INSERE_EMPREGADO
  (PFIRST_NAME    IN VARCHAR2,
   PLAST_NAME     IN VARCHAR2,
   PEMAIL         IN VARCHAR2,
   PPHONE_NUMBER  IN VARCHAR2,
   PHIRE_DATE     IN DATE DEFAULT SYSDATE,
   PJOB_ID        IN VARCHAR2,
   PSALARY        IN NUMBER,
   PCOMISSION_PCT IN NUMBER,
   PMANAGER_ID    IN NUMBER,
   PDEPARTMENT_ID IN NUMBER)
IS 
BEGIN
  INSERT INTO EMPLOYEES (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANGER_ID,
    DEPARTMENT_ID )
  VALUES (
    EMPLOYEES_SEQ.NEXTVAL,
    PFIRST_NAME,
    PLAST_NAME,
    PEMAIL,
    PPHONE_NUMBER,
    PHIRE_DATE,
    PJOB_ID,
    PSALARY,
    PCOMISSION_PCT,
    PMANAGER_ID,
    PDEPARTMENT_ID );
EXCEPTION
  WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20001, 'Erro Oracle ' || SQLCODE || SQLERRM);
END;

BEGIN
  PRC_INSERE_EMPREGADO('David', 'Bowie','DBOWIE','515.127.4861',SYSDATE,'IT_PROG',15000,NULL,103,60);
  COMMIT;
END;