CREATE OR REPLACE PROCEDURE PRC_DISPLAY_EMPOYEES2
  (PEMPLOYEE_ID IN NUMBER)
IS
  EMPLOYEES_CURSOR  SYS_REFCURSOR;
  VFIRST_NAME  EMPLOYEES.FIRST_NAME%TYPE;
  VLAST_NAME   EMPLOYEES.LAST_NAME%TYPE;
BEGIN
  EMPLOYEES_CURSOR := FNC_GET_EMPOYEES(PEMPLOYEE_ID);
  
  LOOP
    FETCH  EMPLOYEES_CURSOR
    INTO   VFIRST_NAME, VLAST_NAME;
    EXIT WHEN EMPLOYEES_CURSOR%NOTFOUND;
	
    DBMS_OUTPUT.PUT_LINE(VFIRST_NAME || ' ' || VLAST_NAME);

  END LOOP;
  
  CLOSE EMPLOYEES_CURSOR;
END PRC_DISPLAY_EMPOYEES2;
