CREATE OR REPLACE PROCEDURE PRC_UPDATE_SALARY
  (PPERCENT IN NUMBER)
AS
  TYPE EMPLOYE_ID_TABLE_TYPE IS TABLE OF EMPLOYES.EMPLOYE_ID%TYPE 
  INDEX BY BINARY_INTEGER;  
  EMPLOYE_ID_TABLE  EMPLOYE_ID_TABLE_TYPE;
BEGIN

  SELECT DISTINCT EMPLOYE_ID 
    BULK COLLECT INTO EMPLOYE_ID_TABLE  
  FROM EMPLOYES;
  
  DBMS_OUTPUT.PUT_LINE('Linhas rEcupEradas: ' || EMPLOYE_ID_TABLE.COUNT);
  
  FORALL I IN 1..EMPLOYE_ID_TABLE.COUNT 
    UPDATE EMPLOYES E
    SET    E.SALARY = E.SALARY * (1 + PPERCENT / 100)
    WHERE  E.EMPLOYE_ID = EMPLOYE_ID_TABLE(I); 
END;