DECLARE
  CURSOR  EMPLOYEES_CURSOR (PJOB_ID VARCHAR2)
  IS
  SELECT  *
  FROM    EMPLOYEES
  WHERE   JOB_ID = PJOB_ID
  FOR UPDATE;
BEGIN
  FOR EMPLOYEES_RECORD IN  EMPLOYEES_CURSOR ('AD_VP')
  LOOP
      UPDATE EMPLOYEES
      SET SALARY = SALARY * (1 + 10 / 100)
      WHERE CURRENT OF EMPLOYEES_CURSOR;
  END LOOP;
  COMMIT;
END;