DECLARE
  CURSOR  EMPLOYEES_CURSOR  IS
  SELECT  *
  FROM    EMPLOYEES;
  EMPLOYEES_RECORD  EMPLOYEES_CURSOR%ROWTYPE; 
BEGIN
  OPEN  EMPLOYEES_CURSOR; 
  
  FETCH  EMPLOYEES_CURSOR  
    INTO  EMPLOYEES_RECORD;
  
  WHILE  EMPLOYEES_CURSOR%FOUND  LOOP
     DBMS_OUTPUT.PUT_LINE(EMPLOYEES_RECORD.EMPLOYEE_ID || ' - ' ||
                         EMPLOYEES_RECORD.FIRST_NAME || ' ' || 
                         EMPLOYEES_RECORD.LAST_NAME || ' - ' ||
                         EMPLOYEES_RECORD.DEPARTMENT_ID || ' - ' ||
                         EMPLOYEES_RECORD.JOB_ID || ' - ' ||
                         EMPLOYEES_RECORD.PHONE_NUMBER || ' - ' ||
                         LTRIM(TO_CHAR(EMPLOYEES_RECORD.SALARY, 'L99G999G999D99')));
    FETCH  EMPLOYEES_CURSOR  
      INTO  EMPLOYEES_RECORD;
  END LOOP;
  
  CLOSE EMPLOYEES_CURSOR;
END;