CREATE OR REPLACE PROCEDURE PRC_INSERE_DATA_AGENDA
IS
BEGIN
  INSERT INTO hr.agenda
  VALUES (agenda_seq.NEXTVAL, SYSDATE);
  COMMIT;
END;

BEGIN
    DBMS_SCHEDULER.CREATE_PROGRAM(
        PROGRAM_NAME => 'HR.PRC_INSERE_AGENDA',
        PROGRAM_ACTION => 'HR.PRC_INSERE_DATA_AGENDA',
        PROGRAM_TYPE => 'STORED_PROCEDURE',
        NUMBER_OF_ARGUMENTS => 0,
        COMMENTS => 'INSERE DADOS NA AGENDA',
        ENABLED => FALSE);

    DBMS_SCHEDULER.ENABLE(NAME=>'HR.PRC_INSERE_AGENDA');    

END;