CREATE OR REPLACE PACKAGE PCK_EMPREGADOS
IS

	GMINSALARY     EMPLOYEES.SALARY%TYPE;

	PROCEDURE PRC_INSERE_EMPREGADO
	(PFIRST_NAME    IN VARCHAR2,
	PLAST_NAME     IN VARCHAR2,
	PEMAIL         IN VARCHAR2,
	PPHONE_NUMBER  IN VARCHAR2,
	PHIRE_DATE     IN DATE DEFAULT SYSDATE,
	PJOB_ID        IN VARCHAR2,
	PSALARY        IN NUMBER,
	PCOMMISSION_PCT IN NUMBER,
	PMANAGER_ID    IN NUMBER,
	PDEPARTMENT_ID IN NUMBER);

	PROCEDURE PRC_AUMENTA_SALARIO_EMPREGADO
	(PEMPLOYEE_ID   IN NUMBER,
	PPERCENT    IN NUMBER);

	FUNCTION FNC_CONSULTA_SALARIO_EMPREGADO
	(PEMPLOYEE_ID   IN NUMBER)
	RETURN NUMBER;

END PCK_EMPREGADOS;