CREATE OR REPLACE 
PACKAGE MY_SCHEMA.EXAMPLE_PACKAGE AS 
  
  NEW_STATUS  VARCHAR2(70) := 'UNKNOWN';
  FUNCTION MULTIPLY(NUM1 INTEGER, NUM2 PLS_INTEGER) RETURN NUMBER;

END MY_SCHEMA.EXAMPLE_PACKAGE;



CREATE OR REPLACE 
PACKAGE BODY MY_SCHEMA.EXAMPLE_PACKAGE AS 
	
  MINIMUM_BALANCE REAL := 100.00; 	
	
  FUNCTION MULTIPLY(NUM1 INTEGER, NUM2 PLS_INTEGER) RETURN NUMBER IS
	TEMP NUMBER;
  BEGIN
	TEMP := NUM1 * NUM2;
	RETURN TEMP;  
  END MULTIPLY;
  
END MY_SCHEMA.EXAMPLE_PACKAGE;