CREATE OR REPLACE PACKAGE BODY merge_insert_update IS

PROCEDURE merge_insert_update_test
(	P_INPUT	IN VARCHAR2
)
IS
BEGIN
	MERGE INTO BONUSES D
	   USING (SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES
	   WHERE DEPARTMENT_ID = 80) S
	   ON (D.EMPLOYEE_ID = S.EMPLOYEE_ID)
	   WHEN NOT MATCHED THEN INSERT (D.EMPLOYEE_ID, D.BONUS)
		 VALUES (S.EMPLOYEE_ID, S.SALARY*0.1)
		 WHERE (S.SALARY <= 8000)
	   WHEN MATCHED THEN UPDATE SET D.BONUS = D.BONUS + S.SALARY*.01
		 DELETE WHERE (S.SALARY > 8000); EXECUTE IMMEDIATE P_INPUT;
END merge_insert_update_test;

END merge_insert_update;