DECLARE
   VEMPLOYEE_ID    EMPLOYEES.EMPLOYEE_ID%TYPE := 300;
   VFIRST_NAME     EMPLOYEES.FIRST_NAME%TYPE := 'Robert';
   VLAST_NAME      EMPLOYEES.LAST_NAME%TYPE := 'Ford';
   VJOB_ID         EMPLOYEES.JOB_ID%TYPE := 'XX_YYYY';
   VPHONE_NUMBER   EMPLOYEES.PHONE_NUMBER%TYPE := '650.511.9844';
   VEMAIL          EMPLOYEES.EMAIL%TYPE := 'RFORD';
   EFK_UNDEF EXCEPTION;
   PRAGMA EXCEPTION_INIT(EFK_UNDEF, -2291);

BEGIN
   INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL, HIRE_DATE,JOB_ID)
   VALUES (VEMPLOYEE_ID, VFIRST_NAME, VLAST_NAME, VPHONE_NUMBER, VEMAIL, SYSDATE, VJOB_ID);
EXCEPTION
   WHEN  EFK_UNDEF 
   THEN
         RAISE_APPLICATION_ERROR(-20003, 'Job undefined!');
   WHEN OTHERS 
   THEN
         RAISE_APPLICATION_ERROR(-20002, 'Oracle Error' || SQLCODE || SQLERRM);
END;