DECLARE
  TYPE NUMBER_TABLE_TYPE IS TABLE OF NUMBER(2) 
  INDEX BY BINARY_INTEGER;
  NUMBER_TABLE  NUMBER_TABLE_TYPE;
BEGIN
  FOR I IN 1..10
  LOOP
    NUMBER_TABLE(I) := I;
  END LOOP;
  FOR I IN 1..10
  LOOP
    DBMS_OUTPUT.PUT_LINE('Associative Array: Indice = ' || TO_CHAR(I) || ', Value = ' || TO_CHAR(NUMBER_TABLE(I)));
  END LOOP;
END;