VARIABLE gMedia NUMBER
DECLARE
  vNumber1  NUMBER(11,2) := 2000;
  vNumber2  NUMBER(11,2) := 5000;
BEGIN  
  :gMedia := (vNumber1 + vNumber2) / 2;
  DBMS_OUTPUT.PUT_LINE('Media = ' || TO_CHAR(:gMedia));
EXCEPTION
  WHEN OTHERS 
  THEN 
    DBMS_OUTPUT.PUT_LINE('Erro Oracle: ' || SQLCODE || SQLERRM);
END;


/*
VARIABLE GMEDIA NUMBER
DECLARE
  VNUMBER1  NUMBER(11,2) := 2000;
  VNUMBER2  NUMBER(11,2) := 5000;
BEGIN  
  :GMEDIA := (VNUMBER1 + VNUMBER2) / 2;
  DBMS_OUTPUT.PUT_LINE('Media = ' || TO_CHAR(:GMEDIA));
EXCEPTION
  WHEN OTHERS 
  THEN 
    DBMS_OUTPUT.PUT_LINE('Erro Oracle: ' || SQLCODE || SQLERRM);
END;
*/